variables:
  packer_version: "1.8.4"
  dind: 20.10-dind
  build_alma: "false"
  build_centos: "false"
  build_rocky8: "false"
  build_rocky9: "false"
  build_oracle: "false"
  build_ubuntu2004: "false"
  build_ubuntu2204: "false"
  build_windows2022_std: "false"
  build_windows2022_dc: "false"
stages:
  - get-packer
  - centos7-validate
  - alma8-validate
  - rocky8-validate
  - rocky9-validate
  - oracle8-validate
  - ubuntu20-validate
  - windows2019-validate
  - windows2022-validate
  - ansible-lint
  - install_packer
  - build_alma
  - build_rocky8
  - build_rocky9
  - build_centos
  - build_oracle
  - build_ubuntu
  - build_windows2022
get-packer:
  stage: get-packer
  image: hashicorp/packer:${packer_version}
  services:
    - docker:$dind
  artifacts:
    expire_in: 1d
    paths:
      - packer
  script:
    - pwd
    - cp -p /bin/packer ./packer
  tags:
    - docker
    - packer
centos79:
  stage: centos7-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_centos7_g2.pkr.hcl"
    - export var_file="./variables/variables_centos79.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
centos79-docker:
  stage: centos7-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_centos7_g2_docker.pkr.hcl"
    - export var_file="./variables/variables_centos79.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
centos79-vagrant:
  stage: centos7-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_centos7_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_centos79.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
alma8:
  stage: alma8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_almalinux8_g2.pkr.hcl"
    - export var_file="./variables/variables_almalinux86.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
alma8-vagrant:
  stage: alma8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_almalinux8_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_almalinux86.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
alma8-docker:
  stage: alma8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_almalinux8_g2_docker.pkr.hcl"
    - export var_file="./variables/variables_almalinux86.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
# Rocky 8
rocky8:
  stage: rocky8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_rockylinux8_g2.pkr.hcl"
    - export var_file="./variables/variables_rockylinux87.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
rocky8-vagrant:
  stage: rocky8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_rockylinux8_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_rockylinux87.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
rocky8-docker:
  stage: rocky8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_rockylinux8_g2_docker.pkr.hcl"
    - export var_file="./variables/variables_rockylinux87.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
# Rocky 9
rocky9:
  stage: rocky9-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_rockylinux9_g2.pkr.hcl"
    - export var_file="./variables/variables_rockylinux91.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
rocky9-docker:
  stage: rocky9-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_rockylinux9_g2_docker.pkr.hcl"
    - export var_file="./variables/variables_rockylinux91.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
# Validate Oracle
oracle8:
  stage: oracle8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_oraclelinux8_g2.pkr.hcl"
    - export var_file="./variables/variables_oraclelinux86.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
oracle8-vagrant:
  stage: oracle8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_oraclelinux8_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_oraclelinux86.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
oracle8-docker:
  stage: oracle8-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_oraclelinux8_g2_docker.pkr.hcl"
    - export var_file="./variables/variables_oraclelinux86.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
ubuntu2004:
  stage: ubuntu20-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_ubuntu2004_g2.pkr.hcl"
    - export var_file="./variables/variables_ubuntu2004.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
ubuntu2204:
  stage: ubuntu20-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_ubuntu2204_g2.pkr.hcl"
    - export var_file="./variables/variables_ubuntu2204.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
lts2019-std:
  stage: windows2019-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2019_g2.pkr.hcl"
    - export var_file="./variables/variables_win2019_std.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
lts2019-std-vagrant:
  stage: windows2019-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2019_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_win2019_std.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
lts2019-dc:
  stage: windows2019-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2019_g2.pkr.hcl"
    - export var_file="./variables/variables_win2019_dc.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
lts2019-dc-vagrant:
  stage: windows2019-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2019_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_win2019_dc.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
# Windows Server 2022
lts2022-std:
  stage: windows2022-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2022_g2.pkr.hcl"
    - export var_file="./variables/variables_win2022_std.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
lts2022-dc:
  stage: windows2022-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2022_g2.pkr.hcl"
    - export var_file="./variables/variables_win2022_dc.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
lts2022-std-vagrant:
  stage: windows2022-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2022_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_win2022_std.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
lts2022-dc-vagrant:
  stage: windows2022-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2022_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_win2022_dc.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - packer
  needs:
    - get-packer
ansible-lint:
  stage: ansible-lint
  image: ${PIPELINE_IMAGE}:${PIPELINE_IMAGE_TAG}
  allow_failure: true
  services:
    - docker:$dind
  before_script:
  - yamllint --version
  - ansible-lint --version
  script:
    - yamllint -c ./.yamllint ./extra/playbooks/*.yaml
    - yamllint -c ./.yamllint ./extra/playbooks/*.yml
    - ansible-lint ./extra/playbooks/*.yaml
  tags:
    - docker
    - packer
  needs:
    - get-packer
# Here building starts
# Install required packer choco package
install_packer:
  variables:
    GIT_STRATEGY: none
  stage: install_packer
  before_script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force -TurnOff -Verbose"
    - Sleep 30
    - "Get-Vm -name packer-*|Remove-VM -Force"
  script:
    - choco upgrade packer --version $packer_version -y
    - packer --version
  tags:
    - windows
    - hyperv
build_alma:
  stage: build_alma
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force -TurnOff -Verbose"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_almalinux86.ps1
  rules:
    - if: $build_alma == "true"
      when: on_success
  tags:
    - windows
    - hyperv
build_alma_docker:
  stage: build_alma
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_almalinux86_docker.ps1
  rules:
    - if: $build_alma == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_alma
build_alma_vagrant:
  stage: build_alma
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_almalinux86_vagrant.ps1
  rules:
    - if: $build_alma == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_alma_docker
# Rocky
build_rocky8:
  stage: build_rocky8
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_rockylinux87.ps1
  rules:
    - if: $build_rocky8 == "true"
      when: on_success
  tags:
    - windows
    - hyperv
build_rocky8_docker:
  stage: build_rocky8
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_rockylinux87_docker.ps1
  rules:
    - if: $build_rocky8 == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_rocky8
build_rocky8_vagrant:
  stage: build_rocky8
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_rockylinux87_vagrant.ps1
  rules:
    - if: $build_rocky8 == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_rocky8_docker
# Rocky 9
build_rocky9:
  stage: build_rocky9
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_rockylinux91.ps1
  rules:
    - if: $build_rocky9 == "true"
      when: on_success
  tags:
    - windows
    - hyperv
build_rocky9_docker:
  stage: build_rocky9
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_rockylinux91_docker.ps1
  rules:
    - if: $build_rocky9 == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_rocky9
build_rocky9_vagrant:
  stage: build_rocky9
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_rockylinux91_vagrant.ps1
  rules:
    - if: $build_rocky9 == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_rocky9_docker
# Build Oracle
build_oracle:
  stage: build_oracle
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_oraclelinux86.ps1
  rules:
    - if: $build_oracle == "true"
      when: on_success
  tags:
    - windows
    - hyperv
build_oracle_docker:
  stage: build_oracle
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_oraclelinux86_docker.ps1
  rules:
    - if: $build_oracle == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_oracle
build_oracle_vagrant:
  stage: build_oracle
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_oraclelinux86_vagrant.ps1
  rules:
    - if: $build_oracle == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_oracle
# CentOS
build_centos:
  stage: build_centos
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_centos79.ps1
  rules:
    - if: $build_centos == "true"
      when: on_success
  tags:
    - windows
    - hyperv
build_centos_docker:
  stage: build_centos
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_centos79_docker.ps1
  rules:
    - if: $build_centos == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_centos
build_centos_vagrant:
  stage: build_centos
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_centos79_vagrant.ps1
  rules:
    - if: $build_centos == "true"
      when: on_success
  tags:
    - windows
    - hyperv
  needs:
    - build_centos_docker
# Ubuntu
build_ubuntu2004:
  stage: build_ubuntu
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_ubuntu2004.ps1
  rules:
    - if: $build_ubuntu2004 == "true"
      when: on_success
  tags:
    - windows
    - hyperv
build_ubuntu2204:
  stage: build_ubuntu
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_ubuntu2204.ps1
  rules:
    - if: $build_ubuntu2204 == "true"
      when: on_success
  tags:
    - windows
    - hyperv
# build windows 2022 std
build_windows_2022_std:
  stage: build_windows2022
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_win2022_std.ps1
  rules:
    - if: $build_windows2022_std == "true"
      when: on_success
  tags:
    - windows
    - hyperv
build_windows_2022_dc:
  stage: build_windows2022
  script:
    - pwd
    - '$env:PACKER_CACHE_DIR="e:\packer_cache"'
    - "Get-Vm -name packer-*|Stop-VM -Force"
    - Sleep 120
    - "Get-Vm -name packer-*|Remove-VM -Force"
    - .\hv_win2022_dc.ps1
  rules:
    - if: $build_windows2022_dc == "true"
      when: on_success
  tags:
    - windows
    - hyperv
