variables:
  packer_version: "1.7.2"
  dind: 20.10-dind
stages:
  - get-packer
  - centos7-packer-validate
  - almalinux8-packer-validate
  - ubuntu20-packer-validate
  - windows2016-packer-validate
  - windows2019-packer-validate
  - windowsserver-packer-validate
get-packer:
  stage: get-packer
  image: alpine
  services:
    - docker:$dind
  artifacts:
    expire_in: 1d
    paths:
      - packer
  script:
    - echo "Fetching packer"
    - wget https://releases.hashicorp.com/packer/"$packer_version"/packer_"$packer_version"_linux_amd64.zip
    - unzip packer_"$packer_version"_linux_amd64.zip
    - chmod +x packer
    - rm -rf packer_"$packer_version"_linux_amd64.zip
  tags:
    - docker
    - shared
centos79:
  stage: centos7-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_centos7_g2.pkr.hcl"
    - export var_file="./variables/variables_centos79.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
centos79-docker:
  stage: centos7-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_centos7_g2_docker.pkr.hcl"
    - export var_file="./variables/variables_centos79.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
centos79-vagrant:
  stage: centos7-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_centos7_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_centos79.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
almalinux84:
  stage: almalinux8-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_almalinux8_g2.pkr.hcl"
    - export var_file="./variables/variables_almalinux84.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
almalinux84-vagrant:
  stage: almalinux8-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_almalinux8_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_almalinux84.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
almalinux84-docker:
  stage: almalinux8-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_almalinux8_g2_docker.pkr.hcl"
    - export var_file="./variables/variables_almalinux84.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
ubuntu2004:
  stage: ubuntu20-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_ubuntu2004_g2.pkr.hcl"
    - export var_file="./variables/variables_ubuntu2004.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
windows2016-std:
  stage: windows2016-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2016_g2.pkr.hcl"
    - export var_file="./variables/variables_win2016_std.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
windows2019-std:
  stage: windows2019-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2019_g2.pkr.hcl"
    - export var_file="./variables/variables_win2019_std.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
windows2019-std-vagrant:
  stage: windows2019-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2019_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_win2019_std.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
windows2019-dc:
  stage: windows2019-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2019_g2.pkr.hcl"
    - export var_file="./variables/variables_win2019_dc.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
windows2019-dc-vagrant:
  stage: windows2019-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_win2019_g2_vagrant.pkr.hcl"
    - export var_file="./variables/variables_win2019_dc.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
windowsserver1909:
  stage: windowsserver-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_winserver_g2.pkr.hcl"
    - export var_file="./variables/variables_winserver_1909.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
windowsserver2004:
  stage: windowsserver-packer-validate
  image: alpine
  services:
    - docker:$dind
  before_script:
    - export template_file="./templates/hv_winserver_g2.pkr.hcl"
    - export var_file="./variables/variables_winserver_2004.pkvars.hcl"
  script:
    - ./packer version --version
    - ./packer validate -var-file="$var_file" "$template_file"
  tags:
    - docker
    - shared
